# Generated by Django 4.2.1 on 2023-06-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_cheque'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='genero',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
