# Generated by Django 4.2.1 on 2023-06-02 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_empleado_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheque',
            name='banco',
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('cheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.cheque')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['id'],
            },
        ),
    ]
