# Generated by Django 4.2.1 on 2023-06-02 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_remove_cheque_banco_banco'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='banco',
            table='banco',
        ),
    ]
