# Generated by Django 4.2.1 on 2023-06-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_alter_banco_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonsocial', models.CharField(max_length=200, verbose_name='Proveedor')),
                ('cuit', models.CharField(max_length=14, verbose_name='CUIT')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
                'ordering': ['id'],
            },
        ),
        migrations.RenameModel(
            old_name='Empleado',
            new_name='Employable',
        ),
    ]
