# Generated by Django 4.2.1 on 2023-06-02 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_proveedor_rename_empleado_employable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proveedor',
            new_name='Proved',
        ),
        migrations.AddField(
            model_name='cheque',
            name='proveedor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='erp.proved'),
            preserve_default=False,
        ),
    ]
