# Generated by Django 4.2.1 on 2023-06-02 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_rename_proveedor_proved_cheque_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banco',
            name='cheque',
        ),
        migrations.AddField(
            model_name='cheque',
            name='banco',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='erp.banco'),
            preserve_default=False,
        ),
    ]
