# Generated by Django 4.2.1 on 2023-06-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_remove_cheque_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='detalle',
            field=models.CharField(default=0, max_length=200, verbose_name='Detalle'),
            preserve_default=False,
        ),
    ]
