# Generated by Django 4.2.1 on 2023-06-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_banco_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='fecha_alta',
            field=models.DateField(auto_now_add=True, default=0, verbose_name='Fecha de Alta'),
            preserve_default=False,
        ),
    ]
