# Generated by Django 4.2.1 on 2023-06-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_banco_fecha_alta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banco',
            name='fecha_alta',
        ),
        migrations.AddField(
            model_name='banco',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True, default=2, verbose_name='Fecha de Ingreso'),
            preserve_default=False,
        ),
    ]
