# Generated by Django 4.2.1 on 2023-06-09 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_remove_banco_fecha_alta_banco_fecha_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='fecha_ingreso',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Ingreso'),
        ),
    ]
