# Generated by Django 4.2.1 on 2023-06-09 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_alter_banco_fecha_ingreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banco',
            name='fecha_ingreso',
        ),
    ]
